name: 'Terraform Workflow'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - okta-dev
      - okta-preview

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set environment variables
      id: vars
      run: |
        BRANCH="${{ github.head_ref || github.ref_name }}"
        if [[ "$BRANCH" == "okta-dev" ]]; then
          echo "TF_WORKSPACE=okta-dev" >> $GITHUB_ENV
        elif [[ "$BRANCH" == "okta-preview" ]]; then
          echo "TF_WORKSPACE=okta-preview" >> $GITHUB_ENV
        else
          echo "TF_WORKSPACE=main" >> $GITHUB_ENV
        fi

    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Select Workspace
      run: terraform workspace select $TF_WORKSPACE || terraform workspace new $TF_WORKSPACE

    - name: Terraform Format Check
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Terraform Apply (only on push to main)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
